# -*- coding: utf-8 -*-
"""stock_analysis_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LxwiBZqVnZzr0MMpvYNYdCctRyBh0CF5
"""

!apt-get install -y unrar

!pip install rarfile

from google.colab import files
import rarfile

uploaded = files.upload()   # upload your data.rar again if needed

rarfile.UNRAR_TOOL = '/usr/bin/unrar'
rf = rarfile.RarFile(list(uploaded.keys())[0])
rf.extractall('stock_data')

print(" Extraction done!")
!ls stock_data

import os

print("Files inside 2023-10 folder:")
print(os.listdir('stock_data/2023-10'))

import yaml

with open('stock_data/2023-10/2023-10-03_05-30-00.yaml', 'r') as f:
    data = yaml.safe_load(f)

print("Type:", type(data))
print("Length:", len(data))

if isinstance(data, list) and len(data) > 0:
    print("First item type:", type(data[0]))
    print("First item keys:", list(data[0].keys()) if isinstance(data[0], dict) else "Not a dictionary")
    print("\nFirst item preview:")
    print(data[0])
else:
    print("Preview:")
    print(data)

import yaml
import pandas as pd
import os
from tqdm import tqdm

all_data = []

for month_folder in os.listdir('stock_data'):
    month_path = os.path.join('stock_data', month_folder)
    if os.path.isdir(month_path):
        for file in tqdm(os.listdir(month_path), desc=f"Processing {month_folder}"):
            if file.endswith('.yaml'):
                with open(os.path.join(month_path, file), 'r') as f:
                    data = yaml.safe_load(f)
                    all_data.extend(data)

df = pd.DataFrame(all_data)
print("Total rows:", len(df))
print("\nColumns:", df.columns.tolist())
print("\nFirst 5 rows:")
print(df.head())

df.to_csv('all_stock_data.csv', index=False)
print("\n Saved as all_stock_data.csv")

print("Total rows in our table:", len(df))
print("How many different companies?", df['Ticker'].nunique())
print("\nFirst 5 rows to see the data:")
print(df.head())

import os

# Create a new folder to keep all 50 CSV files
os.makedirs('stock_csvs', exist_ok=True)

for ticker in df['Ticker'].unique():
    stock_df = df[df['Ticker'] == ticker].copy()
    stock_df.to_csv(f'stock_csvs/{ticker}.csv', index=False)
    print(f" Saved {ticker}.csv")

print("Number of CSV files created:", len(os.listdir('stock_csvs')))

# ============================================================================
# BUG FOUND: CODE EXECUTION ORDER ISSUE
# ============================================================================
# WRONG (Original code - line 91):
#   yearly.to_csv('yearly_returns.csv', index=False)  ← ERROR: 'yearly' undefined!
#   
# The problem:
#   - This tries to save 'yearly' variable that hasn't been defined yet
#   - 'yearly' is defined 60+ lines LATER (around line 155)
#   - Results in corrupted/empty yearly_returns.csv file
# ============================================================================

# CORRECT FIX: Define yearly BEFORE saving it
# Step 3: Calculate Volatility and Daily Returns first
df = df.sort_values(['Ticker', 'date'])                    # Sort by company and date

# Calculate daily return
df['daily_return'] = df.groupby('Ticker')['close'].pct_change()

# Calculate volatility (standard deviation of daily returns)
volatility = df.groupby('Ticker')['daily_return'].std().reset_index()
volatility.columns = ['Ticker', 'volatility']

# Sort to get top 10 most volatile
volatility = volatility.sort_values('volatility', ascending=False)

print(" Volatility calculated for all 50 stocks!")
print("\nTop 10 Most Volatile Stocks:")
print(volatility.head(10))

# Step 4: Calculate Yearly Returns (DEFINE BEFORE SAVING!)
yearly = df.groupby('Ticker').agg(
    first_close=('close', 'first'),
    last_close=('close', 'last')
).reset_index()

yearly['yearly_return_%'] = ((yearly['last_close'] / yearly['first_close']) - 1) * 100
yearly = yearly.sort_values('yearly_return_%', ascending=False)

# NOW SAVE yearly_returns.csv (yearly variable exists!)
yearly.to_csv('yearly_returns.csv', index=False)
print(" Yearly returns saved as yearly_returns.csv")
print("You can now see the file in the left sidebar → Files")

import matplotlib.pyplot as plt

# 1. Save the volatility table
volatility.to_csv('volatility.csv', index=False)
print(" Saved volatility.csv")

# 2. Create the bar chart (exactly as project wants)
top10 = volatility.head(10)

plt.figure(figsize=(12, 6))
plt.bar(top10['Ticker'], top10['volatility'], color='orange')
plt.title('Top 10 Most Volatile Stocks (Past Year)', fontsize=16)
plt.xlabel('Stock Ticker', fontsize=12)
plt.ylabel('Volatility (Standard Deviation)', fontsize=12)
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

print(" Bar chart created!")

import pandas as pd
import plotly.express as px

# ============================================================================
# LOAD PREVIOUSLY CALCULATED DATA (already computed in Step 4)
# ============================================================================
# yearly and volatility are already calculated and saved earlier
# Load them from CSV files

df = pd.read_csv('all_stock_data.csv')
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(by=['Ticker', 'date'])

# Calculate cumulative returns for visualization
df['daily_return'] = df.groupby('Ticker')['close'].pct_change()
df['cumulative_return'] = df.groupby('Ticker')['daily_return'].transform(
    lambda x: (1 + x).cumprod()
) * 100

# Load pre-calculated yearly returns
yearly = pd.read_csv('yearly_returns.csv')

# ============================================================================
# PLOTLY VISUALIZATION: Cumulative Returns Chart
# ============================================================================

df_plotly = df.copy()
top5_tickers = yearly.head(5)['Ticker'].tolist()
df_top5_plotly = df_plotly[df_plotly['Ticker'].isin(top5_tickers)]

fig = px.line(df_top5_plotly,
              x='date',
              y='cumulative_return',
              color='Ticker',
              title='Interactive Cumulative Return of Top 5 Performing Stocks (Past Year)',
              labels={'cumulative_return': 'Cumulative Return (%)', 'date': 'Date'},
              hover_data={'date': '|%b %d', 'cumulative_return': ':.2f'})

fig.update_layout(
    hovermode='x unified',
    title_x=0.5,
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=7,
                     label='1w',
                     step='day',
                     stepmode='backward'),
                dict(count=1,
                     label='1m',
                     step='month',
                     stepmode='backward'),
                dict(count=6,
                     label='6m',
                     step='month',
                     stepmode='backward'),
                dict(count=1,
                     label='YTD',
                     step='year',
                     stepmode='todate'),
                dict(count=1,
                     label='1y',
                     step='year',
                     stepmode='backward'),
                dict(step='all')
            ])
        ),
        rangeslider=dict(
            visible=True
        ),
        type='date'
    )
)

fig.show()

print(" Interactive Cumulative Return Chart created with Plotly!")

import pandas as pd

sector_df = pd.read_csv('Sector_data - Sheet1.csv')
print("Columns:", sector_df.columns.tolist())
print("\nFirst 5 rows:")
print(sector_df.head())

import pandas as pd

# Clean the Symbol column to get clean Ticker (matches our yearly data)
sector_df['Ticker'] = sector_df['Symbol'].str.split(': ').str[1].str.strip()

# Merge sector with yearly returns
sector_performance = pd.merge(
    yearly[['Ticker', 'yearly_return_%']],
    sector_df[['Ticker', 'sector']],
    on='Ticker',
    how='left'
)

# Calculate average yearly return per sector
sector_avg = sector_performance.groupby('sector')['yearly_return_%'].mean().reset_index()
sector_avg = sector_avg.sort_values('yearly_return_%', ascending=False)

print("Sector-wise average return calculated!")
print(sector_avg)

# Create interactive bar chart using Plotly Express
import plotly.express as px

fig = px.bar(sector_avg,
             x='sector',
             y='yearly_return_%',
             title='Average Yearly Return by Sector',
             labels={'yearly_return_%': 'Average Yearly Return (%)', 'sector': 'Sector'},
             # Removed color='sector' to make all bars a single color
             hover_name='sector', # Display sector name on hover
             hover_data={'yearly_return_%': ':.2f%'} # Display percentage with 2 decimal places on hover
            )

fig.update_layout(
    title_x=0.5, # Center the title
    xaxis_tickangle=-45 # Rotate x-axis labels for readability
)

fig.show()

print(" Interactive Sector-wise Performance Bar Chart created!")

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Reload the data
df = pd.read_csv('all_stock_data.csv')

# 2. Convert date column to proper datetime (this fixes the error)
df['date'] = pd.to_datetime(df['date'])

# 3. Create pivot table: rows = date, columns = stocks, values = close price
pivot_table = df.pivot_table(index='date', columns='Ticker', values='close')

# 4. Calculate correlation matrix between all stocks' closing prices
corr_matrix = pivot_table.corr()

# 5. Plot the heatmap
plt.figure(figsize=(14, 10))
sns.heatmap(corr_matrix, cmap='coolwarm', linewidths=0.5)
plt.title('Stock Price Correlation Heatmap (Nifty 50)', fontsize=16)
plt.tight_layout()
plt.show()

print("✅ Correlation Heatmap created successfully!")

import pandas as pd
import matplotlib.pyplot as plt

# Reload data (safe)
df = pd.read_csv('all_stock_data.csv')
df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].dt.to_period('M')

# Calculate monthly return for each stock
monthly = df.groupby(['month', 'Ticker']).agg(
    first_close=('close', 'first'),
    last_close=('close', 'last')
).reset_index()

monthly['monthly_return_%'] = ((monthly['last_close'] / monthly['first_close']) - 1) * 100

# Create bar charts (one per month)
months = sorted(monthly['month'].unique())

# Adjust subplot grid to accommodate all months (14 months, so 7 rows and 2 columns)
fig, axes = plt.subplots(7, 2, figsize=(16, 24))
fig.suptitle('Top 5 Gainers and Losers - Month-wise', fontsize=18)

for i, month in enumerate(months):
    month_data = monthly[monthly['month'] == month].copy()

    # Sort for gainers (descending return) and assign rank
    gainers = month_data.sort_values('monthly_return_%', ascending=False).head(5)
    gainers['rank'] = range(1, len(gainers) + 1)

    # Sort for losers (ascending return) and assign rank
    losers = month_data.sort_values('monthly_return_%', ascending=True).head(5)
    losers['rank'] = range(1, len(losers) + 1)

    ax = axes[i//2, i%2]

    # Collect data for plotting (ordered from Gainer 1 at top to Loser 5 at bottom for display)
    display_labels = []
    display_returns = []
    bar_colors = []      # For the actual bar color
    text_colors = []     # For the y-axis label text color

    # Gainers
    for _, row in gainers.iterrows():
        label = f"{row['rank']}. {row['Ticker']}"
        display_labels.append(label)
        display_returns.append(row['monthly_return_%'])
        if row['monthly_return_%'] >= 0:
            bar_colors.append('green')
            text_colors.append('green')
        else:
            bar_colors.append('red')
            text_colors.append('red') # Gainer with negative return, label text red

    # Losers
    for _, row in losers.iterrows():
        label = f"{row['rank']}. {row['Ticker']}"
        display_labels.append(label)
        display_returns.append(row['monthly_return_%'])
        bar_colors.append('red')
        text_colors.append('red') # Losers, label text red

    # Matplotlib's barh plots from bottom-to-top. To have Gainer 1 at the top and Loser 5 at the bottom,
    # we need to reverse the order of data passed to barh.
    barh_labels = display_labels[::-1]
    barh_returns = display_returns[::-1]
    barh_bar_colors = bar_colors[::-1]
    barh_text_colors = text_colors[::-1] # Also reverse text colors for matching get_yticklabels()

    # Plot the bars
    ax.barh(barh_labels, barh_returns, color=barh_bar_colors)

    # Set the color of the y-axis tick labels
    # ax.get_yticklabels() returns labels in display order (bottom to top)
    for j, tick_label in enumerate(ax.get_yticklabels()):
        tick_label.set_color(barh_text_colors[j])

    ax.set_title(str(month))
    ax.set_xlabel('Monthly Return %')
    # Custom legend to accurately reflect colors
    handles = [plt.Rectangle((0,0),1,1, color='green'), plt.Rectangle((0,0),1,1, color='red')]
    labels = ['Gainers (>=0%)', 'Losers (<0%)']
    ax.legend(handles, labels)

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

print("✅ Month-wise Top 5 Gainers & Losers charts created!")

from sqlalchemy import create_engine
import pandas as pd

# 1. Create SQL database (it will create a file called stock_analysis.db)
engine = create_engine('sqlite:///stock_analysis.db')

# 2. Load the main clean data
df = pd.read_csv('all_stock_data.csv')
df.to_sql('stock_data', engine, if_exists='replace', index=False)

# 3. Also save yearly returns and volatility
yearly.to_sql('yearly_returns', engine, if_exists='replace', index=False)
volatility.to_sql('volatility', engine, if_exists='replace', index=False)

print("✅ Data successfully loaded into SQL Database!")
print("Database file created: stock_analysis.db")
print("Tables created: stock_data, yearly_returns, volatility")





